USE Cinema

CREATE TABLE Film
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(20)
		CONSTRAINT DF_FilmName DEFAULT 'No name',
	Duration INT NOT NULL,
	CONSTRAINT CH_Duration CHECK(Duration > 0),
);

GO

CREATE TABLE Room
(
	RoomId INT PRIMARY KEY IDENTITY,
	SeatsNumber INT
		CONSTRAINT DF_SeatsNumber DEFAULT 100,	
	FilmId INT REFERENCES Film(Id) ON DELETE CASCADE,
	CONSTRAINT CH_SeatsNumber CHECK(SeatsNumber > 0),
);

GO 

CREATE TABLE Ticket
(
	TicketId INT PRIMARY KEY IDENTITY,
	BeginingTime DATETIME NOT NULL,
	RoomId INT REFERENCES Room(RoomId) ON DELETE CASCADE,
	CONSTRAINT CH_BeginingTime CHECK(BeginingTime > 0),
);

GO

CREATE TABLE Visitor
(
	VisitorId INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(20)
		CONSTRAINT DF_VisitorName DEFAULT 'No name',
	TicketId INT REFERENCES Ticket(TicketId) ON DELETE CASCADE,
);

GO

CREATE TABLE Price 
(
	PriceId INT PRIMARY KEY IDENTITY,
	TicketCost INT
		CONSTRAINT DF_TicketCost DEFAULT 10,
	TicektId INT REFERENCES Ticket(TicketId) ON DELETE CASCADE,
);